package world.components;

/* CONE, CUBE, DIAMOND, BALL, KEY, TICKET and TORCH should remain between
 * OUTOFBOUNDS and CHEST
 **/

public enum CellType {
	EMPTY, WALL, DOOR, TELEPORT, OPENDOOR, OUTOFBOUNDS, CONE
	, CUBE, DIAMOND, BALL, KEY, TICKET, TORCH, CHEST, BREIFCASE, DRAWERS
	, TABLE, PLAYER, COUCH, BED;
}